name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      #- master
      #- 'releases/*'
      - ahr-test

jobs:
  build: # make sure build/ci work properly
    #runs-on: ubuntu-latest
    runs-on: [ 'self-hosted' ]
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        jenkins_url: ${{ secrets.JENKINS_URL }}
        username: ${{ secrets.JENKINS_USERNAME }}
        password: ${{ secrets.JENKINS_PASSWORD }}
        job_url: job/jenkins-action
        client_key: ${{ secrets.JENKINS_CLIENT_KEY }}
        client_cert: ${{ secrets.JENKINS_CLIENT_CERT }}
